import Navigation from '@/components/Navigation';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rocket",
  description: "Generated by create next app",
  keywords: ["next", "react", "tailwindcss", "tailwind", "react-tailwind"],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation/>
        {children}</body>
    </html>
  );
}
